package com.example.localization

import androidx.compose.runtime.staticCompositionLocalOf

data class AppStrings(
    // App Identity
    val appName: String = "FoodLoop AI",
    val appTagline: String = "Smart Surplus Food Redistribution",
    val pilotBadge: String = "📍 Narasaraopet Pilot Hub",

    // Common Actions & Navigation
    val home: String = "Home",
    val signIn: String = "Sign In",
    val signOut: String = "Sign Out",
    val register: String = "Register",
    val back: String = "Back",
    val cancel: String = "Cancel",
    val confirm: String = "Confirm",
    val save: String = "Save",
    val submit: String = "Submit",
    val search: String = "Search",
    val filter: String = "Filter",
    val close: String = "Close",
    val viewDetails: String = "VIEW DETAILS",
    val notifications: String = "Notifications",
    val markAllRead: String = "Mark all read",
    val noNotifications: String = "No notifications yet",

    // Language
    val language: String = "Language",
    val selectLanguage: String = "Select Language",
    val searchLanguagePlaceholder: String = "Search any language...",
    val englishDefaultNotice: String = "English is set as default. Choose any language to translate.",
    val languageChangedToast: String = "Language changed successfully",

    // Role Switcher & Isolation
    val roleSwitcherTitle: String = "Switch Active Role",
    val currentRoleLabel: String = "Active Role",
    val donorRole: String = "Food Donor",
    val consumerRole: String = "Care Home Recipient",
    val adminRole: String = "District Administrator",
    val activeSessionLockedNotice: String = "Active Account Session: You must sign out first to open other accounts.",
    val returnHomeRequiresSignOut: String = "You are currently signed in. Only by signing out can you return to Home.",

    // Landing Screen
    val landingHeroTitle: String = "Close the Loop on Surplus Food Waste",
    val landingHeroSubtitle: String = "Connecting colleges, banquets, and hostels with verified orphanages & old age homes across Narasaraopet.",
    val heroStatsPlates: String = "Plates Saved",
    val heroStatsDonors: String = "Active Donors",
    val heroStatsHomes: String = "Care Homes Fed",
    val donorPortalBtn: String = "DONATE FOOD",
    val consumerPortalBtn: String = "RECEIVE FOOD",
    val howItWorksTitle: String = "How FoodLoop Works",
    val mealWindowsTitle: String = "Perishable Food Redistribution Timings",
    val mealWindowsSubtitle: String = "Surplus food has a strict safety shelf-life. Configured meal serving windows:",
    val breakfastTimeLabel: String = "Breakfast: 7:30–9:30 AM",
    val lunchTimeLabel: String = "Lunch: 12:30–3:30 PM",
    val eveningTimeLabel: String = "Evening/Dinner: 7:00–8:30 PM",
    val lateWarningNotice: String = "Late Announcement Warning triggers automatically when <45 mins remain in safe serving window.",

    // Donor Dashboard & Wizard
    val donorDashboardTitle: String = "Donor Coordination Hub",
    val announceSurplusBtn: String = "ANNOUNCE SURPLUS FOOD",
    val activeDonationsSection: String = "My Active Food Announcements",
    val pendingRequestsSection: String = "Inbound Requests for Approval",
    val acceptRequestBtn: String = "Accept Request",
    val declineRequestBtn: String = "Decline",
    val markReadyBtn: String = "Mark Ready for Pickup",
    val markInTransitBtn: String = "Dispatch Transport",
    val platesRemainingLabel: String = "plates remaining",
    val platesTotalLabel: String = "total plates",
    val menuSummaryLabel: String = "Menu",
    val availableUntilLabel: String = "Available until",

    // Consumer Dashboard & Ordering
    val consumerDashboardTitle: String = "Care Home Surplus Portal",
    val availableSurplusSection: String = "Available Surplus Food in Narasaraopet",
    val activeOrdersSection: String = "My Active Food Requests",
    val bookingClosedBadge: String = "⏰ Booking Closed",
    val verifiedDonorBadge: String = "✓ Verified Donor",
    val windowClosedNotice: String = "Window closed",
    val bookingTimeCompletedAlert: String = "The order cutoff time has completed. New requests cannot be placed. Any requests placed beforehand continue proceeding as scheduled.",
    val placeOfficialRequestBtn: String = "PLACE OFFICIAL REQUEST",
    val bookingClosedBtn: String = "BOOKING CLOSED",
    val requestPlatesLabel: String = "Plates Needed",
    val peopleCountLabel: String = "Elder / Children Count",
    val transportPreferenceLabel: String = "Transport Logistics",
    val notesLabel: String = "Dietary or Delivery Notes",

    // Coordination Chat & Tracking
    val coordinationChatTitle: String = "Real-Time Coordination Chat",
    val chatChannelSubtitle: String = "Direct link between Food Donor and Care Home for handoff",
    val typeMessagePlaceholder: String = "Type a message regarding pickup or food packaging...",
    val sendBtn: String = "Send",
    val trackingTitle: String = "Live Order Tracking",
    val orderStatusLabel: String = "Order Status",
    val pickupAddressLabel: String = "Pickup Location",
    val dropAddressLabel: String = "Delivery Location",

    // Verification & Admin
    val adminDashboardTitle: String = "District Administration Control",
    val verifiedStatus: String = "Verified",
    val pendingStatus: String = "Pending Verification",
    val rejectedStatus: String = "Rejected",
    val impactTitle: String = "Platform Impact & Food Redistribution Analytics"
)

val LocalAppStrings = staticCompositionLocalOf { AppStrings() }

object LocalizationProvider {
    fun getStrings(code: String): AppStrings {
        return when (code.lowercase()) {
            "te" -> TeluguStrings
            "hi" -> HindiStrings
            "ta" -> TamilStrings
            "kn" -> KannadaStrings
            "ml" -> MalayalamStrings
            "mr" -> MarathiStrings
            "bn" -> BengaliStrings
            "gu" -> GujaratiStrings
            "es" -> SpanishStrings
            "fr" -> FrenchStrings
            "de" -> GermanStrings
            "ar" -> ArabicStrings
            "zh" -> ChineseStrings
            "ja" -> JapaneseStrings
            "ru" -> RussianStrings
            "pt" -> PortugueseStrings
            "it" -> ItalianStrings
            else -> EnglishStrings
        }
    }

    val EnglishStrings = AppStrings()

    val TeluguStrings = AppStrings(
        appName = "ఫుడ్‌లూప్ AI",
        appTagline = "మిగులు ఆహార పునఃపంపిణీ వ్యవస్థ",
        pilotBadge = "📍 నరసరావుపేట పైలట్ హబ్",
        home = "హోమ్",
        signIn = "లాగిన్ అవ్వండి",
        signOut = "లాగ్ అవుట్",
        register = "రిజిస్టర్ చేసుకోండి",
        back = "వెనుకకు",
        cancel = "రద్దు చేయండి",
        confirm = "ధృవీకరించండి",
        save = "భద్రపరచండి",
        submit = "సమర్పించండి",
        search = "వెతకండి",
        filter = "ఫిల్టర్",
        close = "మూసివేయి",
        viewDetails = "వివరాలు చూడండి",
        notifications = "నోటిఫికేషన్లు",
        markAllRead = "అన్నీ చదివినట్లు గుర్తించు",
        noNotifications = "నోటిఫికేషన్లు ఏవీ లేవు",
        language = "భాష",
        selectLanguage = "భాషను ఎంచుకోండి",
        searchLanguagePlaceholder = "ఏదైనా భాషను వెతకండి...",
        englishDefaultNotice = "డిఫాల్ట్‌గా ఆంగ్లం అమర్చబడింది. అనువదించడానికి ఏదైనా భాషను ఎంచుకోండి.",
        languageChangedToast = "భాష విజయవంతంగా మార్చబడింది",
        roleSwitcherTitle = "పాత్రను మార్చండి",
        currentRoleLabel = "ప్రస్తుత పాత్ర",
        donorRole = "ఆహార దాత",
        consumerRole = "సంరక్షణ గృహం / ఆశ్రమం",
        adminRole = "జిల్లా అడ్మినిస్ట్రేటర్",
        activeSessionLockedNotice = "యాక్టివ్ ఖాతా: ఇతర ఖాతాలను తెరవడానికి ముందు మీరు తప్పనిసరిగా లాగ్ అవుట్ అవ్వాలి.",
        returnHomeRequiresSignOut = "మీరు ప్రస్తుతం లాగిన్ అయి ఉన్నారు. లాగ్ అవుట్ చేయడం ద్వారా మాత్రమే హోమ్ స్క్రీన్‌కు వెళ్లగలరు.",
        landingHeroTitle = "మిగులు ఆహార వృధాను అరికట్టండి",
        landingHeroSubtitle = "నరసరావుపేటలోని కళాశాలలు, ఫంక్షన్ హాళ్లు, హాస్టళ్లను ధృవీకరించబడిన అనాథాశ్రమాలు, వృద్ధాశ్రమాలకు అనుసంధానించండి.",
        heroStatsPlates = "కాపాడిన భోజనాలు",
        heroStatsDonors = "యాక్టివ్ దాతలు",
        heroStatsHomes = "ఆహారం అందిన ఆశ్రమాలు",
        donorPortalBtn = "ఆహారం దానం చేయండి",
        consumerPortalBtn = "ఆహారం పొందండి",
        howItWorksTitle = "ఫుడ్‌లూప్ ఎలా పనిచేస్తుంది",
        mealWindowsTitle = "భోజన సమయాలు & గడువు",
        mealWindowsSubtitle = "ఆహార తాజాదనానికి నిర్దిష్ట సమయం ఉంటుంది. నిర్ణయించిన సమయాలు:",
        breakfastTimeLabel = "ఉపాహారం: 7:30–9:30 AM",
        lunchTimeLabel = "మధ్యాహ్న భోజనం: 12:30–3:30 PM",
        eveningTimeLabel = "సాయంత్రం/రాత్రి భోజనం: 7:00–8:30 PM",
        lateWarningNotice = "సురక్షిత సమయం ముగియడానికి 45 నిమిషాల కంటే తక్కువ ఉన్నప్పుడు హెచ్చరిక వస్తుంది.",
        donorDashboardTitle = "దాతల సమన్వయ కేంద్రం",
        announceSurplusBtn = "మిగులు ఆహారాన్ని ప్రకటించండి",
        activeDonationsSection = "నా క్రియాశీల ఆహార ప్రకటనలు",
        pendingRequestsSection = "ఆమోదం కోసం వచ్చిన అభ్యర్థనలు",
        acceptRequestBtn = "అభ్యర్థనను ఆమోదించండి",
        declineRequestBtn = "తిరస్కరించండి",
        markReadyBtn = "పికప్ కోసం సిద్ధంగా ఉంది",
        markInTransitBtn = "రవాణా ప్రారంభించండి",
        platesRemainingLabel = "ప్లేట్లు మిగిలి ఉన్నాయి",
        platesTotalLabel = "మొత్తం ప్లేట్లు",
        menuSummaryLabel = "మెనూ",
        availableUntilLabel = "అందుబాటులో ఉండే సమయం",
        consumerDashboardTitle = "ఆశ్రమాల ఆహార పోర్టల్",
        availableSurplusSection = "నరసరావుపేటలో అందుబాటులో ఉన్న మిగులు ఆహారం",
        activeOrdersSection = "నా క్రియాశీల ఆహార అభ్యర్థనలు",
        bookingClosedBadge = "⏰ బుకింగ్ ముగిసింది",
        verifiedDonorBadge = "✓ ధృవీకరించబడిన దాత",
        windowClosedNotice = "సమయం ముగిసింది",
        bookingTimeCompletedAlert = "ఆర్డర్ గడువు సమయం పూర్తయింది. కొత్త అభ్యర్థనలు ఉంచలేరు. అంతకుముందు చేసిన అభ్యర్థనలు యథావిధిగా కొనసాగుతాయి.",
        placeOfficialRequestBtn = "అభ్యర్థన పంపండి",
        bookingClosedBtn = "బుకింగ్ ముగిసింది",
        requestPlatesLabel = "కావలసిన ప్లేట్లు",
        peopleCountLabel = "వృద్ధులు / పిల్లల సంఖ్య",
        transportPreferenceLabel = "రవాణా విధానం",
        notesLabel = "డెలివరీ గమనికలు",
        coordinationChatTitle = "రియల్ టైమ్ సమన్వయ చాట్",
        chatChannelSubtitle = "ఆహార దాత మరియు ఆశ్రమం మధ్య ప్రత్యక్ష సంభాషణ",
        typeMessagePlaceholder = "ప్యాకింగ్ లేదా రాక సమయం గురించి సందేశం రాయండి...",
        sendBtn = "పంపు",
        trackingTitle = "లైవ్ ఆర్డర్ ట్రాకింగ్",
        orderStatusLabel = "ఆర్డర్ స్థితి",
        pickupAddressLabel = "పికప్ స్థలం",
        dropAddressLabel = "డెలివరీ స్థలం",
        adminDashboardTitle = "జిల్లా అడ్మినిస్ట్రేషన్ కంట్రోల్",
        verifiedStatus = "ధృవీకరించబడింది",
        pendingStatus = "పరిశీలనలో ఉంది",
        rejectedStatus = "తిరస్కరించబడింది",
        impactTitle = "ప్లాట్‌ఫామ్ ప్రభావం & గణాంకాలు"
    )

    val HindiStrings = AppStrings(
        appName = "फूडलूप AI",
        appTagline = "स्मार्ट अधिशेष भोजन पुनर्वितरण प्रणाली",
        pilotBadge = "📍 नरसारावपेट पायलट हब",
        home = "होम",
        signIn = "साइन इन",
        signOut = "साइन आउट",
        register = "पंजीकरण करें",
        back = "पीछे",
        cancel = "रद्द करें",
        confirm = "पुष्टि करें",
        save = "सहेजें",
        submit = "जमा करें",
        search = "खोजें",
        filter = "फ़िल्टर",
        close = "बंद करें",
        viewDetails = "विवरण देखें",
        notifications = "सूचनाएं",
        markAllRead = "सभी को पढ़ा हुआ चिह्नित करें",
        noNotifications = "कोई सूचना नहीं है",
        language = "भाषा",
        selectLanguage = "भाषा चुनें",
        searchLanguagePlaceholder = "कोई भी भाषा खोजें...",
        englishDefaultNotice = "अंग्रेजी डिफ़ॉल्ट रूप से सेट है। अनुवाद के लिए कोई भी भाषा चुनें।",
        languageChangedToast = "भाषा सफलतापूर्वक बदली गई",
        roleSwitcherTitle = "भूमिका बदलें",
        currentRoleLabel = "वर्तमान भूमिका",
        donorRole = "भोजन दाता",
        consumerRole = "आश्रम / देखभाल केंद्र",
        adminRole = "जिला प्रशासक",
        activeSessionLockedNotice = "सक्रिय सत्र: दूसरे खाते खोलने के लिए आपको पहले साइन आउट करना होगा।",
        returnHomeRequiresSignOut = "आप वर्तमान में साइन इन हैं। केवल साइन आउट करके ही आप होम पर लौट सकते हैं।",
        landingHeroTitle = "अधिशेष भोजन की बर्बादी को रोकें",
        landingHeroSubtitle = "कॉलेजों, बैंक्वेट हॉल और छात्रावासों को नरसारावपेट के सत्यापित अनाथालयों और वृद्धाश्रमों से जोड़ना।",
        heroStatsPlates = "बचाई गई थालियां",
        heroStatsDonors = "सक्रिय दाता",
        heroStatsHomes = "लाभान्वित आश्रम",
        donorPortalBtn = "भोजन दान करें",
        consumerPortalBtn = "भोजन प्राप्त करें",
        howItWorksTitle = "फूडलूप कैसे काम करता है",
        mealWindowsTitle = "सुरक्षित भोजन पुनर्वितरण समय",
        mealWindowsSubtitle = "अधिशेष भोजन की गुणवत्ता बनाए रखने के लिए निर्धारित समय:",
        breakfastTimeLabel = "नाश्ता: 7:30–9:30 AM",
        lunchTimeLabel = "दोपहर का भोजन: 12:30–3:30 PM",
        eveningTimeLabel = "शाम/रात का भोजन: 7:00–8:30 PM",
        lateWarningNotice = "सुरक्षित समय समाप्त होने में 45 मिनट से कम समय रहने पर चेतावनी दिखाई देती है।",
        donorDashboardTitle = "दाता समन्वय केंद्र",
        announceSurplusBtn = "अधिशेष भोजन की घोषणा करें",
        activeDonationsSection = "मेरी सक्रिय भोजन घोषणाएं",
        pendingRequestsSection = "स्वीकृति हेतु अनुरोध",
        acceptRequestBtn = "अनुरोध स्वीकार करें",
        declineRequestBtn = "अस्वीकार करें",
        markReadyBtn = "पिकअप के लिए तैयार",
        markInTransitBtn = "परिवहन रवाना करें",
        platesRemainingLabel = "थालियां शेष",
        platesTotalLabel = "कुल थालियां",
        menuSummaryLabel = "मेनू",
        availableUntilLabel = "उपलब्ध समय तक",
        consumerDashboardTitle = "आश्रम भोजन पोर्टल",
        availableSurplusSection = "नरसारावपेट में उपलब्ध अधिशेष भोजन",
        activeOrdersSection = "मेरे सक्रिय भोजन अनुरोध",
        bookingClosedBadge = "⏰ बुकिंग बंद",
        verifiedDonorBadge = "✓ सत्यापित दाता",
        windowClosedNotice = "समय समाप्त",
        bookingTimeCompletedAlert = "ऑर्डर कटऑफ समय समाप्त हो चुका है। नए अनुरोध नहीं किए जा सकते। पहले से किए गए अनुरोध सुचारू रूप से जारी रहेंगे।",
        placeOfficialRequestBtn = "अनुरोध भेजें",
        bookingClosedBtn = "बुकिंग बंद",
        requestPlatesLabel = "आवश्यक थालियां",
        peopleCountLabel = "बुजुर्गों / बच्चों की संख्या",
        transportPreferenceLabel = "परिवहन व्यवस्था",
        notesLabel = "वितरण संबंधी निर्देश",
        coordinationChatTitle = "रियल-टाइम समन्वय चैट",
        chatChannelSubtitle = "दाता और आश्रम के बीच सीधा संपर्क",
        typeMessagePlaceholder = "पिकअप या समय के संबंध में संदेश लिखें...",
        sendBtn = "भेजें",
        trackingTitle = "लाइव ऑर्डर ट्रैकिंग",
        orderStatusLabel = "ऑर्डर स्थिति",
        pickupAddressLabel = "पिकअप का पता",
        dropAddressLabel = "वितरण का पता",
        adminDashboardTitle = "जिला प्रशासनिक नियंत्रण",
        verifiedStatus = "सत्यापित",
        pendingStatus = "सत्यापन लंबित",
        rejectedStatus = "अस्वीकृत",
        impactTitle = "प्लेटफ़ॉर्म प्रभाव और विश्लेषण"
    )

    val TamilStrings = AppStrings(
        appName = "ஃபுட்லூப் AI",
        appTagline = "உணவு மறுபகிர்வு தளம்",
        pilotBadge = "📍 நரசராவ்பேட்டை மையம்",
        home = "முகப்பு",
        signIn = "உள்நுழைக",
        signOut = "வெளியேறு",
        register = "பதிவு செய்க",
        back = "பின்னே",
        cancel = "ரத்து",
        confirm = "உறுதி செய்",
        save = "சேமி",
        submit = "சமர்ப்பி",
        search = "தேடு",
        viewDetails = "விவரங்களை காண்க",
        notifications = "அறிவிப்புகள்",
        markAllRead = "அனைத்தும் படித்தவை",
        language = "மொழி",
        selectLanguage = "மொழியை தேர்வு செய்க",
        searchLanguagePlaceholder = "எந்த மொழியையும் தேடுங்கள்...",
        languageChangedToast = "மொழி வெற்றிகரமாக மாற்றப்பட்டது",
        roleSwitcherTitle = "பங்கை மாற்றுக",
        activeSessionLockedNotice = "செயலில் உள்ள கணக்கு: பிற கணக்குகளை திறக்க முதலில் வெளியேற வேண்டும்.",
        returnHomeRequiresSignOut = "நீங்கள் உள்நுழைந்துள்ளீர்கள். வெளியேறுவதன் மூலம் மட்டுமே முகப்புக்கு செல்ல முடியும்.",
        landingHeroTitle = "உணவு வீணாவதை தடுப்போம்",
        landingHeroSubtitle = "நரசராவ்பேட்டையின் கல்வி நிறுவனங்கள் மற்றும் உணவுக்கூடங்களை முதியோர் இல்லங்களுடன் இணைக்கிறது.",
        heroStatsPlates = "சேமிக்கப்பட்ட உணவுகள்",
        heroStatsDonors = "செயலில் உள்ள நன்கொடையாளர்கள்",
        heroStatsHomes = "பயன்பெற்ற இல்லங்கள்",
        donorPortalBtn = "உணவு வழங்குக",
        consumerPortalBtn = "உணவு பெறுக",
        mealWindowsTitle = "உணவு விநியோக நேரங்கள்",
        breakfastTimeLabel = "காலை உணவு: 7:30–9:30 AM",
        lunchTimeLabel = "மதிய உணவு: 12:30–3:30 PM",
        eveningTimeLabel = "இரவு உணவு: 7:00–8:30 PM",
        bookingClosedBadge = "⏰ முன்பதிவு முடிந்தது",
        bookingTimeCompletedAlert = "முன்பதிவு நேரம் முடிந்துவிட்டது. புதிய கோரிக்கைகளை சமர்ப்பிக்க முடியாது. ஏற்கனவே சமர்ப்பிக்கப்பட்ட கோரிக்கைகள் வழக்கம் போல் செயல்படும்.",
        placeOfficialRequestBtn = "கோரிக்கையை அனுப்பு",
        bookingClosedBtn = "முன்பதிவு முடிந்தது",
        coordinationChatTitle = "நேரடி ஒருங்கிணைப்பு அரட்டை"
    )

    val KannadaStrings = AppStrings(
        appName = "ಫುಡ್‌ಲೂಪ್ AI",
        appTagline = "ಹೆಚ್ಚುವರಿ ಆಹಾರ ಮರುಹಂಚಿಕೆ ವ್ಯವಸ್ಥೆ",
        pilotBadge = "📍 ನರಸರಾವ್‌ಪೇಟೆ ಹಬ್",
        home = "ಮುಖಪುಟ",
        signIn = "ಸೈನ್ ಇನ್",
        signOut = "ಸೈನ್ ಔಟ್",
        register = "ನೋಂದಾಯಿಸಿ",
        back = "ಹಿಂದೆ",
        cancel = "ರದ್ದುಮಾಡಿ",
        confirm = "ದೃಢೀಕರಿಸಿ",
        save = "ಉಳಿಸಿ",
        submit = "ಸಲ್ಲಿಸಿ",
        search = "ಹುಡುಕಿ",
        viewDetails = "ವಿವರಗಳನ್ನು ವೀಕ್ಷಿಸಿ",
        notifications = "ಸೂಚನೆಗಳು",
        language = "ಭಾಷೆ",
        selectLanguage = "ಭಾಷೆಯನ್ನು ಆಯ್ಕೆಮಾಡಿ",
        searchLanguagePlaceholder = "ಯಾವುದೇ ಭಾಷೆಯನ್ನು ಹುಡುಕಿ...",
        languageChangedToast = "ಭಾಷೆ ಯಶಸ್ವಿಯಾಗಿ ಬದಲಾಗಿದೆ",
        roleSwitcherTitle = "ಪಾತ್ರ ಬದಲಾಯಿಸಿ",
        activeSessionLockedNotice = "ಸಕ್ರಿಯ ಖಾತೆ: ಇತರ ಖಾತೆಗಳನ್ನು ತೆರೆಯಲು ಮೊದಲು ಸೈನ್ ಔಟ್ ಮಾಡಿ.",
        returnHomeRequiresSignOut = "ನೀವು ಪ್ರಸ್ತುತ ಸೈನ್ ಇನ್ ಆಗಿದ್ದೀರಿ. ಸೈನ್ ಔಟ್ ಮಾಡುವ ಮೂಲಕ ಮಾತ್ರ ಮುಖಪುಟಕ್ಕೆ ಹೋಗಬಹುದು.",
        landingHeroTitle = "ಆಹಾರ ವ್ಯರ್ಥವಾಗುವುದನ್ನು ತಡೆಯಿರಿ",
        landingHeroSubtitle = "ಶಿಕ್ಷಣ ಸಂಸ್ಥೆಗಳು ಮತ್ತು ಮದುವೆ ಮಂಟಪಗಳನ್ನು ನರಸರಾವ್‌ಪೇಟೆಯ ವೃದ್ಧಾಶ್ರಮಗಳೊಂದಿಗೆ ಸಂಪರ್ಕಿಸುತ್ತದೆ.",
        heroStatsPlates = "ಉಳಿಸಿದ ಊಟಗಳು",
        heroStatsDonors = "ದಾನಿಗಳು",
        heroStatsHomes = "ಆಶ್ರಮಗಳು",
        donorPortalBtn = "ಆಹಾರ ದಾನ ಮಾಡಿ",
        consumerPortalBtn = "ಆಹಾರ ಪಡೆಯಿರಿ",
        mealWindowsTitle = "ಆಹಾರ ವಿತರಣಾ ಸಮಯಗಳು",
        breakfastTimeLabel = "ಬೆಳಗಿನ ಉಪಹಾರ: 7:30–9:30 AM",
        lunchTimeLabel = "ಮಧ್ಯಾಹ್ನದ ಊಟ: 12:30–3:30 PM",
        eveningTimeLabel = "ರಾತ್ರಿಯ ಊಟ: 7:00–8:30 PM",
        bookingClosedBadge = "⏰ ಬುಕಿಂಗ್ ಮುಕ್ತಾಯ",
        bookingTimeCompletedAlert = "ಆರ್ಡರ್ ಸಮಯ ಮುಗಿದಿದೆ. ಹೊಸ ವಿನಂತಿಗಳನ್ನು ಇರಿಸಲಾಗುವುದಿಲ್ಲ. ಮೊದಲೇ ಇರಿಸಲಾದ ವಿನಂತಿಗಳು ಮುಂದುವರಿಯುತ್ತವೆ.",
        placeOfficialRequestBtn = "ವಿನಂತಿ ಕಳುಹಿಸಿ",
        bookingClosedBtn = "ಬುಕಿಂಗ್ ಮುಕ್ತಾಯ",
        coordinationChatTitle = "ನೈಜ-ಸಮಯದ ಸಮನ್ವಯ ಚಾಟ್"
    )

    val MalayalamStrings = AppStrings(
        appName = "ഫുഡ്‌ലൂപ്പ് AI",
        appTagline = "മിച്ചഭക്ഷണ പുനർവിതരണ പ്ലാറ്റ്‌ഫോം",
        pilotBadge = "📍 നരസറാവുപേട്ട് പൈലറ്റ് ഹബ്",
        home = "ഹോം",
        signIn = "സൈൻ ഇൻ",
        signOut = "സൈൻ ഔട്ട്",
        register = "രജിസ്റ്റർ ചെയ്യുക",
        language = "ഭാഷ",
        selectLanguage = "ഭാഷ തിരഞ്ഞെടുക്കുക",
        mealWindowsTitle = "ഭക്ഷണ വിതരണ സമയങ്ങൾ",
        eveningTimeLabel = "അത്താഴം: 7:00–8:30 PM",
        bookingClosedBadge = "⏰ ബുക്കിംഗ് അവസാനിച്ചു",
        bookingClosedBtn = "ബുക്കിംഗ് അവസാനിച്ചു"
    )

    val MarathiStrings = AppStrings(
        appName = "फूडलूप AI",
        appTagline = "अतिरिक्त अन्न पुनर्वितरण प्रणाली",
        pilotBadge = "📍 नरसारावपेट पायलट केंद्र",
        home = "होम",
        signIn = "साइन इन",
        signOut = "साइन आउट",
        register = "नोंदणी करा",
        language = "भाषा",
        selectLanguage = "भाषा निवडा",
        mealWindowsTitle = "अन्न पुनर्वितरण वेळा",
        eveningTimeLabel = "रात्रीचे जेवण: 7:00–8:30 PM",
        bookingClosedBadge = "⏰ बुकिंग बंद",
        bookingClosedBtn = "बुकिंग बंद"
    )

    val BengaliStrings = AppStrings(
        appName = "ফুডলুপ AI",
        appTagline = "উদ্বৃত্ত খাবার পুনর্বন্টন প্ল্যাটফর্ম",
        pilotBadge = "📍 নরসারাওপেট পাইলট হাব",
        home = "হোম",
        signIn = "সাইন ইন",
        signOut = "সাইন আউট",
        register = "নিবন্ধন করুন",
        language = "ভাষা",
        selectLanguage = "ভাষা নির্বাচন করুন",
        mealWindowsTitle = "খাবার বিতরণের সময়সূচী",
        eveningTimeLabel = "সান্ধ্য/নৈশভোজ: 7:00–8:30 PM",
        bookingClosedBadge = "⏰ বুকিং সমাপ্ত",
        bookingClosedBtn = "বুকিং বন্ধ"
    )

    val GujaratiStrings = AppStrings(
        appName = "ફૂડલૂપ AI",
        appTagline = "વધારાના અન્ન પુનર્વિતરણ પ્રણાલી",
        pilotBadge = "📍 નરસારાવપેટ હબ",
        home = "હોમ",
        signIn = "સાઇન ઇન",
        signOut = "સાઇન આઉટ",
        register = "નોંધણી કરો",
        language = "ભાષા",
        selectLanguage = "ભાષા પસંદ કરો",
        mealWindowsTitle = "ભોજન વિતરણ સમય",
        eveningTimeLabel = "સાંજ/રાત્રિ ભોજન: 7:00–8:30 PM",
        bookingClosedBadge = "⏰ બુકિંગ બંધ",
        bookingClosedBtn = "બુકિંગ બંધ"
    )

    val SpanishStrings = AppStrings(
        appName = "FoodLoop AI",
        appTagline = "Redistribución Inteligente de Alimentos Excedentes",
        pilotBadge = "📍 Centro Piloto Narasaraopet",
        home = "Inicio",
        signIn = "Iniciar Sesión",
        signOut = "Cerrar Sesión",
        register = "Registrarse",
        back = "Atrás",
        cancel = "Cancelar",
        confirm = "Confirmar",
        save = "Guardar",
        submit = "Enviar",
        search = "Buscar",
        filter = "Filtrar",
        close = "Cerrar",
        viewDetails = "VER DETALLES",
        notifications = "Notificaciones",
        markAllRead = "Marcar todo como leído",
        language = "Idioma",
        selectLanguage = "Seleccionar Idioma",
        searchLanguagePlaceholder = "Buscar cualquier idioma...",
        languageChangedToast = "Idioma cambiado con éxito",
        roleSwitcherTitle = "Cambiar Rol",
        donorRole = "Donante de Alimentos",
        consumerRole = "Hogar de Cuidado",
        adminRole = "Administrador del Distrito",
        activeSessionLockedNotice = "Sesión Activa: Debe cerrar sesión antes de abrir otras cuentas.",
        returnHomeRequiresSignOut = "Ha iniciado sesión. Solo al cerrar sesión puede volver a Inicio.",
        landingHeroTitle = "Evitemos el Desperdicio de Alimentos",
        landingHeroSubtitle = "Conectando instituciones excedentes con orfanatos y hogares de ancianos verificados.",
        heroStatsPlates = "Platos Salvados",
        heroStatsDonors = "Donantes Activos",
        heroStatsHomes = "Hogares Atendidos",
        donorPortalBtn = "DONAR ALIMENTOS",
        consumerPortalBtn = "RECIBIR ALIMENTOS",
        mealWindowsTitle = "Horarios de Redistribución de Alimentos",
        breakfastTimeLabel = "Desayuno: 7:30–9:30 AM",
        lunchTimeLabel = "Almuerzo: 12:30–3:30 PM",
        eveningTimeLabel = "Cena / Noche: 7:00–8:30 PM",
        bookingClosedBadge = "⏰ Reserva Cerrada",
        verifiedDonorBadge = "✓ Donante Verificado",
        windowClosedNotice = "Ventana cerrada",
        bookingTimeCompletedAlert = "La hora límite de pedidos ha finalizado. No se pueden realizar nuevos pedidos. Los pedidos realizados previamente continuarán normalmente.",
        placeOfficialRequestBtn = "ENVIAR SOLICITUD",
        bookingClosedBtn = "RESERVA CERRADA",
        coordinationChatTitle = "Chat de Coordinación en Tiempo Real",
        typeMessagePlaceholder = "Escriba un mensaje sobre recogida o entrega...",
        sendBtn = "Enviar"
    )

    val FrenchStrings = AppStrings(
        appName = "FoodLoop AI",
        appTagline = "Redistribution Intelligente des Excédents Alimentaires",
        pilotBadge = "📍 Centre Pilote Narasaraopet",
        home = "Accueil",
        signIn = "Connexion",
        signOut = "Déconnexion",
        register = "S'inscrire",
        back = "Retour",
        cancel = "Annuler",
        confirm = "Confirmer",
        language = "Langue",
        selectLanguage = "Sélectionner la langue",
        searchLanguagePlaceholder = "Rechercher une langue...",
        languageChangedToast = "Langue modifiée avec succès",
        mealWindowsTitle = "Horaires de Sécurité Alimentaire",
        eveningTimeLabel = "Dîner / Soir : 7:00–8:30 PM",
        bookingClosedBadge = "⏰ Réservation Fermée",
        bookingTimeCompletedAlert = "L'heure limite de commande est terminée. Aucune nouvelle commande ne peut être passée. Les commandes préalablement validées se poursuivent normalement.",
        placeOfficialRequestBtn = "COMMANDER",
        bookingClosedBtn = "RÉSERVATION FERMÉE"
    )

    val GermanStrings = AppStrings(
        appName = "FoodLoop AI",
        appTagline = "Intelligente Lebensmittel-Umverteilung",
        pilotBadge = "📍 Pilotzentrum Narasaraopet",
        home = "Startseite",
        signIn = "Anmelden",
        signOut = "Abmelden",
        register = "Registrieren",
        language = "Sprache",
        selectLanguage = "Sprache auswählen",
        searchLanguagePlaceholder = "Sprache suchen...",
        mealWindowsTitle = "Verteilungszeitfenster",
        eveningTimeLabel = "Abendessen: 7:00–8:30 PM",
        bookingClosedBadge = "⏰ Buchung Beendet",
        bookingTimeCompletedAlert = "Die Buchungsfrist ist abgelaufen. Es können keine neuen Anfragen gestellt werden. Vorherige Anfragen werden regulär weiterbearbeitet.",
        bookingClosedBtn = "BUCHUNG GESCHLOSSEN"
    )

    val ArabicStrings = AppStrings(
        appName = "فودلوب AI",
        appTagline = "إعادة توزيع فائض الطعام الذكي",
        pilotBadge = "📍 مركز ناراساراوپيت التجريبي",
        home = "الرئيسية",
        signIn = "تسجيل الدخول",
        signOut = "تسجيل الخروج",
        register = "إنشاء حساب",
        language = "اللغة",
        selectLanguage = "اختر اللغة",
        searchLanguagePlaceholder = "ابحث عن أي لغة...",
        mealWindowsTitle = "أوقات توزيع الوجبات الآمنة",
        eveningTimeLabel = "العشاء / المساء: 7:00–8:30 PM",
        bookingClosedBadge = "⏰ تم إغلاق الحجز",
        bookingTimeCompletedAlert = "اكتمل وقت الحجز النهائي. لا يمكن تقديم طلبات جديدة. الطلبات المقدمة مسبقًا مستمرة في مسارها كالمعتاد.",
        placeOfficialRequestBtn = "إرسال الطلب",
        bookingClosedBtn = "الحجز مغلق"
    )

    val ChineseStrings = AppStrings(
        appName = "FoodLoop AI",
        appTagline = "智能余食再分配平台",
        pilotBadge = "📍 纳拉萨拉奥佩特示范中心",
        home = "首页",
        signIn = "登录",
        signOut = "退出登录",
        register = "注册",
        language = "语言",
        selectLanguage = "选择语言",
        searchLanguagePlaceholder = "搜索任何语言...",
        mealWindowsTitle = "食物保鲜与分发时间窗口",
        eveningTimeLabel = "晚餐/晚间: 7:00–8:30 PM",
        bookingClosedBadge = "⏰ 预订已截止",
        bookingTimeCompletedAlert = "订单截止时间已到。无法提交新申请。在此之前提交的申请将继续照常执行配送。",
        placeOfficialRequestBtn = "提交正式申请",
        bookingClosedBtn = "预订截止"
    )

    val JapaneseStrings = AppStrings(
        appName = "FoodLoop AI",
        appTagline = "食品ロス削減・余剰食品マッチング",
        pilotBadge = "📍 ナラサラオペト実証ハブ",
        home = "ホーム",
        signIn = "サインイン",
        signOut = "サインアウト",
        register = "登録",
        language = "言語",
        selectLanguage = "言語を選択",
        searchLanguagePlaceholder = "言語を検索...",
        mealWindowsTitle = "安全な食品再分配タイムテーブル",
        eveningTimeLabel = "夕食 / 夜間: 7:00–8:30 PM",
        bookingClosedBadge = "⏰ 受付終了",
        bookingTimeCompletedAlert = "注文締切時間が終了しました。新規リクエストは受け付けられません。事前に成立したリクエストは予定通り配送が継続されます。",
        placeOfficialRequestBtn = "リクエスト送信",
        bookingClosedBtn = "受付終了"
    )

    val RussianStrings = AppStrings(
        appName = "FoodLoop AI",
        appTagline = "Система перераспределения излишков еды",
        pilotBadge = "📍 Пилотный хаб Нарасараопет",
        home = "Главная",
        signIn = "Войти",
        signOut = "Выйти",
        register = "Регистрация",
        language = "Язык",
        selectLanguage = "Выберите язык",
        searchLanguagePlaceholder = "Поиск языка...",
        eveningTimeLabel = "Ужин / вечер: 7:00–8:30 PM",
        bookingClosedBadge = "⏰ Прием заказов закрыт",
        bookingClosedBtn = "ЗАКАЗ ЗАКРЫТ"
    )

    val PortugueseStrings = AppStrings(
        appName = "FoodLoop AI",
        appTagline = "Redistribuição Inteligente de Alimentos Excedentes",
        pilotBadge = "📍 Centro Piloto Narasaraopet",
        home = "Início",
        signIn = "Entrar",
        signOut = "Sair",
        register = "Cadastrar",
        language = "Idioma",
        selectLanguage = "Selecionar Idioma",
        searchLanguagePlaceholder = "Pesquisar qualquer idioma...",
        eveningTimeLabel = "Jantar / Noite: 7:00–8:30 PM",
        bookingClosedBadge = "⏰ Reservas Encerradas",
        bookingClosedBtn = "RESERVA ENCERRADA"
    )

    val ItalianStrings = AppStrings(
        appName = "FoodLoop AI",
        appTagline = "Ridistribuzione Intelligente delle Eccedenze Alimentari",
        pilotBadge = "📍 Centro Pilota Narasaraopet",
        home = "Home",
        signIn = "Accedi",
        signOut = "Disconnetti",
        register = "Registrati",
        language = "Lingua",
        selectLanguage = "Seleziona lingua",
        searchLanguagePlaceholder = "Cerca qualsiasi lingua...",
        eveningTimeLabel = "Cena / Sera: 7:00–8:30 PM",
        bookingClosedBadge = "⏰ Prenotazioni Chiuse",
        bookingClosedBtn = "PRENOTAZIONI CHIUSE"
    )
}
